apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mytestapp
  namespace: argocd
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  source:
    chart: frontend-img
    helm:
      parameters:
      - name: hello
        value: helloqa
      - name: bye
        value: byedev
      - name: city
        value: hyderabad
      - name: helo00000000
        value: iiiiiiiiiii
      - name: ssssssssssss
        value: rrrrrrrrrrrrrr
    repoURL: ghcr.io/srikanthhg
    targetRevision: 25.03.79
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
