AWSTemplateFormatVersion: '2010-09-09'
Description: Create IAM Role and attach Policy

Resources:
  MyRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MyExampleRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /

  MyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: MyExamplePolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:ListAllMyBuckets
              - s3:GetObject
            Resource: "*"
      Roles:
        - !Ref MyRole

Outputs:
  RoleName:
    Value: !Ref MyRole
  PolicyName:
    Value: !Ref MyPolicy
