name: package helm chart

on:
    push: 
        branches: ["main"]

env:
    registry_name: "oci://ghcr.io/srikanthhg"

jobs:
    publish-helm:
        # outputs:
          # steps.fetch_path.outputs.
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repo
            uses: actions/checkout@v4

          - name: Install Helm
            uses: azure/setup-helm@v4
            with:
                version: v3.15.2
            
          - name: Set up Helm registry login
            run: |
                echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username ${{ github.actor }}  --password-stdin
        
          - name: Detect changed chart(s)
            id: fetch_path
            run: |
                # List changed files in charts/ folder
                git diff --name-only ${{ github.event.before }} ${{ github.sha }} > modified_files.txt
                cat modified_files.txt


          # - name: Package & Push Helm Chart(s)
          #   if: steps.changed.outputs.charts != ''
          #   run: |
          #       version=25.0.${{github.run_number}}
          #       for chart in ${{ steps.changed.outputs.charts }}; do
          #           echo "📦 Packaging chart: $chart"
          #           helm dependency update charts/$chart
          #           helm package charts/$chart-${version} --destination .
                    
          #           FILE=$(ls ${chart}-${version}*.tgz)
          #           echo "🚀 Pushing $FILE"
          #           helm push "$FILE" oci://ghcr.io/${{ github.repository_owner }}/helm
          #       done