name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'

    - name: Install NuGet CLI
      run: |
       wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -O nuget.exe
       chmod +x nuget.exe
    
    
    - name: Download NuGet package and extract dependencies
      run: |
       mono nuget.exe install Microsoft.Extensions.DependencyInjection -Version 8.0.0 -OutputDirectory ./packages
       echo "Dependencies for Microsoft.Extensions.DependencyInjection:"
       cat ./packages/Microsoft.Extensions.DependencyInjection.8.0.0/Microsoft.Extensions.DependencyInjection.nuspec
